### ISSUE TITLE
Приведение имён к стандарту CamelCase

### ISSUE THREAD

**Issue by rZinnatov** [Armageddontoday/Hellow-world#1]
Будем сразу следовать общепринятым стандартам, чтобы вырабатывать правильные привычки. Программа будет работать в любом случае, но мы будем сразу привыкать писать код для людей. Т.к. пишем мы код один раз, а всё остальное время его будут читать.

Именование в принципе на самом деле очень важная штука, но важность её становится видна лишь на больших проектах.

**Comment by Armageddontoday** [comment]
Done.
