### ISSUE TITLE
Проверка на знание таблицы умножения

### ISSUE THREAD

**Issue by rZinnatov** [Armageddontoday/Hellow-world#2]
1. Программа выводит на экран **задание** - информацию вида "x * y = ", где x, y - целые числа
2. Программа предлагает пользователю совершить ввод данных
3. Программа проверяет ввод:
  1. Если введено число, то программа трактует его как результат, проверяет и выводит на экран оповещение, был ли результат верным (в случае неверного результата, программа также выводит правильный результат). Программа переходит к пункту 1.
  2. Если введена строка "exit", то программа завершает выполнение
  3. Иначе, программа предлагает ещё раз произвести ввод к текущему **заданию**

**Comment by Armageddontoday** [comment]
done
