### ISSUE TITLE
Отдельный класс для методов вывода строк

### ISSUE THREAD

**Issue by rZinnatov** [Armageddontoday/Hellow-world#4]
Необходимо создать класс, который соберёт в себя все методы вывода строк на экран. Такие как ErrorLines, CorrectAnswer, etc.

Конечный класс и его методы НЕ должны быть static.

**Comment by Armageddontoday** [comment]
Добавил класс "ScreenLines", вынес в него методы. Получается класс отличается от отдельных методов тем, что содержит их и лежит в отдельном файле, что позволяет работать с ним отдельно от основного массива кода?

**Comment by rZinnatov** [comment]
Всё верно. И помимо методов, класс может содержать данные, которые формируют его **state**.
